version: "3.9"

# Run 'docker compose up' to start all containers

# Default Network
networks:
  app-network:
    driver: bridge

services:

  # ETCD Server
  etcd:
    image: 'bitnami/etcd:3.4.15'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-network

  # Memcached Server
  memcached:
    image: 'bitnami/memcached:1.6.9'
    networks:
      - app-network

  authserver1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=auth-server
    depends_on:
      - etcd
      - memcached
    networks:
      - app-network

  authserver2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=auth-server
    depends_on:
      - etcd
      - memcached
    networks:
      - app-network

  geoserver1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=geo-server
    depends_on:
      - etcd
      - memcached
    networks:
      - app-network

  geoserver2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=geo-server
    depends_on:
      - etcd
      - memcached
    networks:
      - app-network

  authclient:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=auth-client
    depends_on:
      - etcd
      - authserver1
      - authserver2
    networks:
      - app-network

  geoclient:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=geo-client
    depends_on:
      - etcd
      - geoserver1
      - geoserver2
    networks:
      - app-network

#  etcd-client:
#    image: 'distribuidos:0.1.0'
#    # entrypoint: '/opt/docker/bin/etcd-demo'
#    command: sh -c "gradle etcd"
#    depends_on:
#      - etcd
#      - memcached
#    networks:
#      - app-network